# Generated by Django 4.2.8 on 2023-12-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='Phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
