# Generated by Django 4.2.8 on 2023-12-09 15:42

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_applicant_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='Phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
